"""
Django settings for eud_test project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_yaml_config():
    """Load configuration from YAML file if specified, otherwise return defaults."""
    config_file = os.environ.get("EUD_CONFIG_FILE", "")
    
    if not config_file:
        return None
    
    try:
        import yaml
        with open(config_file, 'r') as f:
            config = yaml.safe_load(f)
            # Convert list values to single values (take first element)
            if config:
                for key, value in config.items():
                    if isinstance(value, list) and len(value) > 0:
                        config[key] = value[0]
            return config
    except FileNotFoundError:
        print(f"Warning: Config file '{config_file}' not found. Using defaults.")
        return None
    except ImportError:
        print("Warning: PyYAML not installed. Using defaults.")
        return None
    except Exception as e:
        print(f"Warning: Error loading config file: {e}. Using defaults.")
        return None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tk=+xj%^g!r@fm@==!9pc9zorcpocg(ai1t6abh4)_ufynb=^5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'django_filters',
    'simple_history',

    # Local apps
    'apps.core',
    'apps.users',
    'apps.clients',
    'apps.clients_le',
    'apps.generic_crud',
    'apps.audit',
    'apps.dashboard_bots',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.users.middleware.DevSSOMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ),
}

ROOT_URLCONF = 'eud_gui.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eud_gui.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_config = _load_yaml_config()

if _config and _config.get("DATABASE_TYPE") == "postgres":
    certs_path = _config.get("certs_path")
    db_env = _config.get("db_env")
    schema = _config.get("schema")

    from europe_domestic_utils.src.database_wrapper import Database_Config

    db_config = Database_Config(certs_path=certs_path, db_env=db_env)
    conn_data = db_config.get_connection_data()

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": conn_data.get("database"),
            "USER": conn_data.get("user"),
            "PASSWORD": conn_data.get("password"),
            "HOST": conn_data.get("host"),
            "PORT": conn_data.get("port", 5432),
            "OPTIONS": {
                "options": f"-c search_path={schema}",
                "sslcert": conn_data.get("sslcert"),
                "sslkey": conn_data.get("sslkey"),
                "sslrootcert": conn_data.get("sslrootcert"),
            } if any(conn_data.get(k) for k in ("sslcert", "sslkey", "sslrootcert")) else {},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

LOGIN_URL = '/admin/login/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'
