# Generated by Django 6.0.6 on 2026-06-26 07:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario_id', models.CharField(help_text='e.g. A_NP_RES', max_length=50, unique=True)),
                ('name', models.CharField(help_text='e.g. "A - Natural Person Resident"', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalScenario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('scenario_id', models.CharField(db_index=True, help_text='e.g. A_NP_RES', max_length=50)),
                ('name', models.CharField(help_text='e.g. "A - Natural Person Resident"', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical scenario',
                'verbose_name_plural': 'historical scenarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentRequirement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('cdok', models.CharField(max_length=100, verbose_name='Document Code (CDOK)')),
                ('duplicate', models.BooleanField(default=False)),
                ('granularity', models.CharField(help_text='e.g. "One for each Co-owner"', max_length=255)),
                ('output_folder_structure', models.CharField(blank=True, max_length=500, null=True)),
                ('input_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_template', models.TextField(blank=True, max_length=100, null=True, verbose_name='PDF Template')),
                ('rules_special_conditions', models.TextField(blank=True, null=True, verbose_name='Rules/Special Conditions')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='repapering.scenario')),
            ],
            options={
                'verbose_name': 'historical document requirement',
                'verbose_name_plural': 'historical document requirements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cdok', models.CharField(max_length=100, verbose_name='Document Code (CDOK)')),
                ('duplicate', models.BooleanField(default=False)),
                ('granularity', models.CharField(help_text='e.g. "One for each Co-owner"', max_length=255)),
                ('output_folder_structure', models.CharField(blank=True, max_length=500, null=True)),
                ('input_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf_template', models.FileField(blank=True, null=True, upload_to='repapering_templates/', verbose_name='PDF Template')),
                ('rules_special_conditions', models.TextField(blank=True, null=True, verbose_name='Rules/Special Conditions')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='repapering.scenario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
