# Generated by Django 6.0.6 on 2026-06-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequirement',
            name='input_filename',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentrequirement',
            name='input_filename',
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='granularity',
            field=models.CharField(choices=[('One for each Co-owner', 'One for each Co-owner'), ('One for each BO', 'One for each BO'), ('One for each LR', 'One for each LR'), ('One for each POA', 'One for each POA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaldocumentrequirement',
            name='granularity',
            field=models.CharField(choices=[('One for each Co-owner', 'One for each Co-owner'), ('One for each BO', 'One for each BO'), ('One for each LR', 'One for each LR'), ('One for each POA', 'One for each POA')], max_length=255),
        ),
    ]
