# Generated by Django 6.0.6 on 2026-06-26 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapering', '0002_remove_documentrequirement_input_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequirement',
            name='rules_special_conditions',
        ),
        migrations.RemoveField(
            model_name='historicaldocumentrequirement',
            name='rules_special_conditions',
        ),
        migrations.RemoveField(
            model_name='historicalscenario',
            name='description',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='description',
        ),
        migrations.AlterField(
            model_name='historicalscenario',
            name='scenario_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
