# Generated by Django 6.0.6 on 2026-06-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repapering', '0003_remove_documentrequirement_rules_special_conditions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscenario',
            name='scenario_id',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='scenario_id',
        ),
    ]
