# Generated by Django 6.0.6 on 2026-06-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapering', '0004_remove_historicalscenario_scenario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequirement',
            name='granularity',
            field=models.CharField(blank=True, choices=[('One for each Co-owner', 'One for each Co-owner'), ('One for each BO', 'One for each BO'), ('One for each LR', 'One for each LR'), ('One for each POA', 'One for each POA')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldocumentrequirement',
            name='granularity',
            field=models.CharField(blank=True, choices=[('One for each Co-owner', 'One for each Co-owner'), ('One for each BO', 'One for each BO'), ('One for each LR', 'One for each LR'), ('One for each POA', 'One for each POA')], max_length=255, null=True),
        ),
    ]
