# Generated by Django 6.0.5 on 2026-07-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapering', '0005_alter_documentrequirement_granularity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequirement',
            name='pdf_template',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='repapering_templates/', verbose_name='PDF Template'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentrequirement',
            name='pdf_template',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='PDF Template'),
        ),
    ]
