# Generated by Django 6.0.5 on 2026-07-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repapering', '0006_alter_documentrequirement_pdf_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscenario',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='pdf_template',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='templates/', verbose_name='PDF Template'),
        ),
        migrations.DeleteModel(
            name='HistoricalDocumentRequirement',
        ),
        migrations.DeleteModel(
            name='HistoricalScenario',
        ),
    ]
