# Generated by Django 6.0.3 on 2026-03-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=255)),
                ('bank_rel', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('client_type', models.CharField(blank=True, max_length=100, null=True)),
                ('t_number', models.CharField(blank=True, max_length=100, null=True)),
                ('run_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crud_gui_dashboard_records_2',
            },
        ),
        migrations.CreateModel(
            name='BotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.CharField(max_length=255, unique=True)),
                ('bot_status', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Bot Statuses',
                'db_table': 'crud_gui_dashboard_bots',
            },
        ),
    ]
