# Generated by Django 6.0.3 on 2026-03-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankingrelationship',
            name='status',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='historicalbankingrelationship',
            name='status',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
