# Generated by Django 6.0.3 on 2026-03-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientadvisor',
            name='first_and_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalclientadvisor',
            name='first_and_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='first_and_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='first_and_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
