# Generated by Django 6.0.3 on 2026-03-12 15:52

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(db_index=True)),
                ('portfolio_uuid', models.UUIDField(db_index=True)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(db_index=True)),
                ('comm_type', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email')], max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('is_main', models.BooleanField(default=False, verbose_name='Main Contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('client_uuid', models.UUIDField(db_index=True)),
                ('portfolio_uuid', models.UUIDField(db_index=True)),
                ('account_number', models.CharField(db_index=True, max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical account',
                'verbose_name_plural': 'historical accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCommunication',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('client_uuid', models.UUIDField(db_index=True)),
                ('comm_type', models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email')], max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('is_main', models.BooleanField(default=False, verbose_name='Main Contact')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical communication',
                'verbose_name_plural': 'historical communications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNationality',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('client_uuid', models.UUIDField(db_index=True)),
                ('country', models.CharField(max_length=100)),
                ('is_main', models.BooleanField(default=False, verbose_name='Main Nationality')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical nationality',
                'verbose_name_plural': 'historical Nationalities',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPortfolio',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('client_uuid', models.UUIDField(db_index=True)),
                ('portfolio_number', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical portfolio',
                'verbose_name_plural': 'historical portfolios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(db_index=True)),
                ('country', models.CharField(max_length=100)),
                ('is_main', models.BooleanField(default=False, verbose_name='Main Nationality')),
            ],
            options={
                'verbose_name_plural': 'Nationalities',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(db_index=True)),
                ('portfolio_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldocument',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpersonaldata',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrelationship',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='PersonalData',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='historicaladdress',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical address', 'verbose_name_plural': 'historical Addresses'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='historicalclient',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='country',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='email',
        ),
        migrations.AddField(
            model_name='address',
            name='is_domicile',
            field=models.BooleanField(default=False, verbose_name='Domicile Address'),
        ),
        migrations.AddField(
            model_name='address',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Main Address'),
        ),
        migrations.AddField(
            model_name='address',
            name='is_tax_domicile',
            field=models.BooleanField(default=False, verbose_name='Tax Domicile'),
        ),
        migrations.AddField(
            model_name='address',
            name='tin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TIN Number'),
        ),
        migrations.AddField(
            model_name='client',
            name='br_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='Business Relation (BR)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='is_domicile',
            field=models.BooleanField(default=False, verbose_name='Domicile Address'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Main Address'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='is_tax_domicile',
            field=models.BooleanField(default=False, verbose_name='Tax Domicile'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='tin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TIN Number'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='br_number',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=50, verbose_name='Business Relation (BR)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('frozen', 'Frozen')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('frozen', 'Frozen')], default='active', max_length=50),
        ),
        migrations.DeleteModel(
            name='HistoricalContract',
        ),
        migrations.DeleteModel(
            name='HistoricalDocument',
        ),
        migrations.DeleteModel(
            name='HistoricalPersonalData',
        ),
        migrations.DeleteModel(
            name='HistoricalRelationship',
        ),
    ]
