# Generated by Django 6.0.3 on 2026-04-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_additionalformde_limited_power_of_attorney_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankingrelationship',
            name='language',
            field=models.CharField(blank=True, choices=[('German', 'German'), ('English', 'English'), ('Italian', 'Italian'), ('Spanish', 'Spanish')], max_length=50, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='bankingrelationship',
            name='segment_type',
            field=models.CharField(blank=True, choices=[('120', '120'), ('132', '132'), ('131', '131')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='communication_context',
            field=models.CharField(blank=True, choices=[('work', 'work'), ('private', 'private')], max_length=255, null=True, verbose_name='context'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='prefix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='prefix'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='type_of_communication',
            field=models.CharField(blank=True, choices=[('Telephone', 'Telephone'), ('Mobile', 'Mobile'), ('Email', 'Email'), ('Pec address', 'Pec address'), ('Fax', 'Fax')], max_length=255, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='historicalbankingrelationship',
            name='language',
            field=models.CharField(blank=True, choices=[('German', 'German'), ('English', 'English'), ('Italian', 'Italian'), ('Spanish', 'Spanish')], max_length=50, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='historicalbankingrelationship',
            name='segment_type',
            field=models.CharField(blank=True, choices=[('120', '120'), ('132', '132'), ('131', '131')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunication',
            name='communication_context',
            field=models.CharField(blank=True, choices=[('work', 'work'), ('private', 'private')], max_length=255, null=True, verbose_name='context'),
        ),
        migrations.AlterField(
            model_name='historicalcommunication',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='historicalcommunication',
            name='prefix',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='prefix'),
        ),
        migrations.AlterField(
            model_name='historicalcommunication',
            name='type_of_communication',
            field=models.CharField(blank=True, choices=[('Telephone', 'Telephone'), ('Mobile', 'Mobile'), ('Email', 'Email'), ('Pec address', 'Pec address'), ('Fax', 'Fax')], max_length=255, null=True, verbose_name='type'),
        ),
    ]
