# Generated by Django 6.0.3 on 2026-03-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_additionalformde_bankingrelationship_clientadvisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalportfolio',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.RemoveField(
            model_name='account',
            name='portfolio_uuid',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='portfolio_uuid',
        ),
        migrations.AddField(
            model_name='account',
            name='product_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='product_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalPortfolio',
        ),
    ]
