# Generated by Django 6.0.3 on 2026-03-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_account_communication_historicalaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalportfolio',
            name='portfolio_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_number',
            field=models.CharField(max_length=50),
        ),
    ]
