# Generated by Django 6.0.4 on 2026-05-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_bankingrelationship_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnationality',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnationality',
            name='fiscal_code_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnationality',
            name='id_document_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnationality',
            name='id_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnationality',
            name='is_id_document_provided',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnationality',
            name='is_main_nationality',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnationality',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnationality',
            name='nci',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnationality',
            name='release_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnationality',
            name='release_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='investment_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment Amount'),
        ),
        migrations.AlterField(
            model_name='historicaltin',
            name='aei_tin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AEI/TIN'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='fiscal_code_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='id_document_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='id_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='is_id_document_provided',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='is_main_nationality',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='nci',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='release_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='release_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='investment_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Investment Amount'),
        ),
        migrations.AlterField(
            model_name='tin',
            name='aei_tin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AEI/TIN'),
        ),
    ]
