# Generated by Django 6.0.4 on 2026-05-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_historicalnationality_fiscal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrelationship',
            name='relationship_with_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='relationship with owner'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='relationship_with_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='relationship with owner'),
        ),
    ]
