# Generated by Django 6.0.5 on 2026-05-08 09:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_ebanking_first_and_last_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CDOKList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(db_index=True)),
                ('cdok', models.CharField(blank=True, max_length=255, null=True)),
                ('signed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True)),
                ('valid_from', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_until', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='historicalpersonalinformation',
            name='technical_account',
        ),
        migrations.RemoveField(
            model_name='historicalpersonalinformation',
            name='type_of_relationship',
        ),
        migrations.RemoveField(
            model_name='historicalrelationship',
            name='tax_domicile',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='technical_account',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='type_of_relationship',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='tax_domicile',
        ),
        migrations.AddField(
            model_name='address',
            name='additional_address_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='additional address (1)'),
        ),
        migrations.AddField(
            model_name='address',
            name='additional_address_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='additional address (2)'),
        ),
        migrations.AddField(
            model_name='address',
            name='canton_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='canton/state'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='region'),
        ),
        migrations.AddField(
            model_name='clientadvisor',
            name='gpn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GPN'),
        ),
        migrations.AddField(
            model_name='communication',
            name='is_main_contact',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='additional_address_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='additional address (1)'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='additional_address_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='additional address (2)'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='canton_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='canton/state'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='region'),
        ),
        migrations.AddField(
            model_name='historicalclientadvisor',
            name='gpn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GPN'),
        ),
        migrations.AddField(
            model_name='historicalcommunication',
            name='is_main_contact',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='additional_designation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional designation'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='ao_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AO number'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='correspondence_language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correspondence language'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='country_of_issue_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country of issue (ID)'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='form_of_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Form of address'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID number'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='identificationsnummer_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificationsnummer (DE)'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='release_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='release country'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='sae_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SAE code'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='historicalrelationship',
            name='signature_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='signature type'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='additional_designation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional designation'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='ao_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AO number'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='correspondence_language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correspondence language'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='country_of_issue_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country of issue (ID)'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='form_of_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Form of address'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID number'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='identificationsnummer_de',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Identificationsnummer (DE)'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='release_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='release country'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='sae_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SAE code'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='signature_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='signature type'),
        ),
        migrations.AlterField(
            model_name='historicalnationality',
            name='is_id_document_provided',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnationality',
            name='is_main_nationality',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpersonalinformation',
            name='fiscal_it_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fiscal code (IT)'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='is_id_document_provided',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='is_main_nationality',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='fiscal_it_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fiscal code (IT)'),
        ),
        migrations.CreateModel(
            name='HistoricalCDOKList',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('client_uuid', models.UUIDField(db_index=True)),
                ('cdok', models.CharField(blank=True, max_length=255, null=True)),
                ('signed', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True)),
                ('valid_from', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_until', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cdok list',
                'verbose_name_plural': 'historical cdok lists',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
