# Generated by Django 6.0.5 on 2026-05-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_cdoklist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address (email)'),
        ),
        migrations.AlterField(
            model_name='historicalcommunication',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address (email)'),
        ),
    ]
