# Generated by Django 6.0.5 on 2026-05-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_historicaltaxdomicile_taxdomicile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnationality',
            name='fiscal_code',
        ),
        migrations.RemoveField(
            model_name='historicalnationality',
            name='fiscal_code_path',
        ),
        migrations.RemoveField(
            model_name='historicalpersonalinformation',
            name='fiscal_identifier',
        ),
        migrations.RemoveField(
            model_name='historicalpersonalinformation',
            name='type_id_NCI',
        ),
        migrations.RemoveField(
            model_name='historicaltaxdomicile',
            name='fiscal_residence',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='fiscal_code',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='fiscal_code_path',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='fiscal_identifier',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='type_id_NCI',
        ),
        migrations.RemoveField(
            model_name='taxdomicile',
            name='fiscal_residence',
        ),
        migrations.AddField(
            model_name='historicaltaxdomicile',
            name='fiscal_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fiscal identifier'),
        ),
        migrations.AddField(
            model_name='historicaltaxdomicile',
            name='tax_domicile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tax domicile'),
        ),
        migrations.AddField(
            model_name='taxdomicile',
            name='fiscal_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fiscal identifier'),
        ),
        migrations.AddField(
            model_name='taxdomicile',
            name='tax_domicile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tax domicile'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type_of_address',
            field=models.CharField(blank=True, choices=[('Correspondence', 'Correspondence'), ('Domicile', 'Domicile'), ('Residence', 'Residence'), ('Tax domicile', 'Tax domicile'), ('Fiscal residence', 'Fiscal residence'), ('Third party', 'Third party')], max_length=100, null=True, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='type_of_address',
            field=models.CharField(blank=True, choices=[('Correspondence', 'Correspondence'), ('Domicile', 'Domicile'), ('Residence', 'Residence'), ('Tax domicile', 'Tax domicile'), ('Fiscal residence', 'Fiscal residence'), ('Third party', 'Third party')], max_length=100, null=True, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='historicalnationality',
            name='id_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='type of identification (NCI)'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='id_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='type of identification (NCI)'),
        ),
    ]
