# Generated by Django 6.0.5 on 2026-06-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_remove_bankingrelationship_fiscal_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankingrelationship',
            name='code_ksc',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalbankingrelationship',
            name='code_ksc',
        ),
        migrations.RemoveField(
            model_name='historicalcommunication',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalpersonalinformation',
            name='country_of_issue_id',
        ),
        migrations.RemoveField(
            model_name='historicalpersonalinformation',
            name='form_of_address',
        ),
        migrations.RemoveField(
            model_name='historicalpersonalinformation',
            name='release_authority',
        ),
        migrations.RemoveField(
            model_name='historicalpersonalinformation',
            name='release_country',
        ),
        migrations.RemoveField(
            model_name='historicalpersonalinformation',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='historicalpersonalinformation',
            name='release_place',
        ),
        migrations.RemoveField(
            model_name='historicalpersonalinformation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='historicalrelationship',
            name='technical_account',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='country_of_issue_id',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='form_of_address',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='release_authority',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='release_country',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='release_place',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='technical_account',
        ),
        migrations.AddField(
            model_name='bankingrelationship',
            name='csc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CSC'),
        ),
        migrations.AddField(
            model_name='communication',
            name='email_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address (email)'),
        ),
        migrations.AddField(
            model_name='historicalbankingrelationship',
            name='csc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CSC'),
        ),
        migrations.AddField(
            model_name='historicalcommunication',
            name='email_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address (email)'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Date of issue'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='id_place_of_issue_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place of issue (city)'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Issuing authority'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='place_of_issue_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place of issue (city)'),
        ),
        migrations.AddField(
            model_name='historicalpersonalinformation',
            name='place_of_issue_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place of issue (country)'),
        ),
        migrations.AddField(
            model_name='historicalrelationship',
            name='br_technical_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BR-Technical Account'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True, verbose_name='Date of issue'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='id_place_of_issue_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place of issue (city)'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Issuing authority'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='place_of_issue_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place of issue (city)'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='place_of_issue_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='place of issue (country)'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='br_technical_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BR-Technical Account'),
        ),
        migrations.AlterField(
            model_name='bankingrelationship',
            name='id_doc_provided',
            field=models.CharField(blank=True, choices=[('Provided', 'Provided'), ('Not provided', 'Not provided')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='communication',
            name='type_of_communication',
            field=models.CharField(blank=True, choices=[('Fixed Number', 'Fixed Number'), ('Mobile', 'Mobile'), ('Email', 'Email'), ('Pec address', 'Pec address'), ('Fax', 'Fax')], max_length=255, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='historicalbankingrelationship',
            name='id_doc_provided',
            field=models.CharField(blank=True, choices=[('Provided', 'Provided'), ('Not provided', 'Not provided')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunication',
            name='type_of_communication',
            field=models.CharField(blank=True, choices=[('Fixed Number', 'Fixed Number'), ('Mobile', 'Mobile'), ('Email', 'Email'), ('Pec address', 'Pec address'), ('Fax', 'Fax')], max_length=255, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='alternative_investment',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='currency_hedging',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='share_focus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrelationship',
            name='type_of_relationship',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Co-owner', 'Co-owner'), ('POA (for all accounts)', 'POA (for all accounts)'), ('POA (general)', 'POA (general)'), ('POA (limited)', 'POA (limited)'), ('POA (in case of death)', 'POA (in case of death)'), ('POA (Information)', 'POA (Information)'), ('Beneficial Owner', 'Beneficial Owner'), ('Legal Representative + Beneficial Owner', 'Legal Representative + Beneficial Owner')], max_length=100, null=True, verbose_name='relationship'),
        ),
        migrations.AlterField(
            model_name='product',
            name='alternative_investment',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency_hedging',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='share_focus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='type_of_relationship',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Co-owner', 'Co-owner'), ('POA (for all accounts)', 'POA (for all accounts)'), ('POA (general)', 'POA (general)'), ('POA (limited)', 'POA (limited)'), ('POA (in case of death)', 'POA (in case of death)'), ('POA (Information)', 'POA (Information)'), ('Beneficial Owner', 'Beneficial Owner'), ('Legal Representative + Beneficial Owner', 'Legal Representative + Beneficial Owner')], max_length=100, null=True, verbose_name='relationship'),
        ),
    ]
