# Generated by Django 6.0.5 on 2026-06-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_remove_bankingrelationship_code_ksc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='alternative_investment',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='currency_hedging',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='share_focus',
        ),
        migrations.RemoveField(
            model_name='product',
            name='alternative_investment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='currency_hedging',
        ),
        migrations.RemoveField(
            model_name='product',
            name='share_focus',
        ),
        migrations.AlterField(
            model_name='address',
            name='type_of_address',
            field=models.CharField(blank=True, choices=[('Correspondence', 'Correspondence'), ('Domicile', 'Domicile'), ('Permanent', 'Permanent'), ('Tax domicile', 'Tax domicile'), ('Fiscal residence', 'Fiscal residence'), ('Third party', 'Third party')], max_length=100, null=True, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='type_of_address',
            field=models.CharField(blank=True, choices=[('Correspondence', 'Correspondence'), ('Domicile', 'Domicile'), ('Permanent', 'Permanent'), ('Tax domicile', 'Tax domicile'), ('Fiscal residence', 'Fiscal residence'), ('Third party', 'Third party')], max_length=100, null=True, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='historicalpersonalinformation',
            name='id_place_of_issue_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='country of issue (id)'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='id_place_of_issue_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='country of issue (id)'),
        ),
    ]
