# Generated by Django 6.0.5 on 2026-06-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_remove_historicalproduct_alternative_investment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RemoveField(
            model_name='bankingrelationship',
            name='id_doc_provided',
        ),
        migrations.RemoveField(
            model_name='historicalbankingrelationship',
            name='id_doc_provided',
        ),
        migrations.DeleteModel(
            name='HistoricalAccount',
        ),
    ]
