# Generated by Django 6.0.5 on 2026-06-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_delete_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type_of_address',
            field=models.CharField(blank=True, choices=[('Correspondence', 'Correspondence'), ('Domicile', 'Domicile'), ('Permanent', 'Permanent')], max_length=100, null=True, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='type_of_address',
            field=models.CharField(blank=True, choices=[('Correspondence', 'Correspondence'), ('Domicile', 'Domicile'), ('Permanent', 'Permanent')], max_length=100, null=True, verbose_name='address type'),
        ),
    ]
