# Generated by Django 6.0.5 on 2026-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_alter_address_type_of_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankingrelationship',
            name='client_segment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Segment'),
        ),
        migrations.AlterField(
            model_name='bankingrelationship',
            name='segment_type',
            field=models.CharField(blank=True, choices=[('120', '120'), ('132', '132'), ('131', '131')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbankingrelationship',
            name='client_segment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Segment'),
        ),
        migrations.AlterField(
            model_name='historicalbankingrelationship',
            name='segment_type',
            field=models.CharField(blank=True, choices=[('120', '120'), ('132', '132'), ('131', '131')], max_length=255, null=True),
        ),
    ]
