# Generated by Django 6.0.7 on 2026-07-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_alter_bankingrelationship_client_segment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmeetingpreparation',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='MeetingPreparation',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='rei_no_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Remboursement, Discount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='rei_no_discount_amount_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remboursement, Discount, Amount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='rei_no_flat_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Remboursement, Fee'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='rei_no_flat_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remboursement, Fee, Amount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='remboursements',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Remboursement'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='salesroom_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salesroom Code'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='shares_fixed_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares + Fixed Income, Discount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='shares_fixed_discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares + Fixed Income, Discount Amount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='shares_fixed_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares + Fixed Income, Fee'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='shares_fixed_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares + Fixed Income, Fee Amount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='shares_fixed_funds_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares + Fixed Income + Funds, Discount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='shares_fixed_funds_discount_amou',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares + Fixed Income, Discount Amount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='shares_fixed_funds_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares + Fixed Income + Funds, Fee'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='shares_fixed_funds_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares + Fixed Income + Funds, Fee Amount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='tra_no_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Transaction, Discount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='tra_no_discount_amount_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction, Discount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='tra_no_flat_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Transaction, Fee, Amount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='tra_no_flat_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction, Fee, Amount'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='withdrawal_sent_to',
            field=models.CharField(blank=True, choices=[('To client', 'To client'), ('To Client Advisor', 'To Client Advisor'), ('Digitally', 'Digitally')], max_length=50, null=True, verbose_name='Sending of documents'),
        ),
        migrations.AddField(
            model_name='product',
            name='rei_no_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Remboursement, Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='rei_no_discount_amount_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remboursement, Discount, Amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='rei_no_flat_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Remboursement, Fee'),
        ),
        migrations.AddField(
            model_name='product',
            name='rei_no_flat_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remboursement, Fee, Amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='remboursements',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Remboursement'),
        ),
        migrations.AddField(
            model_name='product',
            name='salesroom_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salesroom Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='shares_fixed_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares + Fixed Income, Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='shares_fixed_discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares + Fixed Income, Discount Amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='shares_fixed_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares + Fixed Income, Fee'),
        ),
        migrations.AddField(
            model_name='product',
            name='shares_fixed_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares + Fixed Income, Fee Amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='shares_fixed_funds_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares + Fixed Income + Funds, Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='shares_fixed_funds_discount_amou',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares + Fixed Income, Discount Amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='shares_fixed_funds_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares + Fixed Income + Funds, Fee'),
        ),
        migrations.AddField(
            model_name='product',
            name='shares_fixed_funds_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares + Fixed Income + Funds, Fee Amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='tra_no_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Transaction, Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='tra_no_discount_amount_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction, Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='tra_no_flat_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Transaction, Fee, Amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='tra_no_flat_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction, Fee, Amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='withdrawal_sent_to',
            field=models.CharField(blank=True, choices=[('To client', 'To client'), ('To Client Advisor', 'To Client Advisor'), ('Digitally', 'Digitally')], max_length=50, null=True, verbose_name='Sending of documents'),
        ),
        migrations.AlterField(
            model_name='bankingrelationship',
            name='account_and_securities_statements',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Transaction Statements'),
        ),
        migrations.AlterField(
            model_name='bankingrelationship',
            name='communication_br',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Communication Mode'),
        ),
        migrations.AlterField(
            model_name='bankingrelationship',
            name='type_and_purpose',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Purpose Of Banking Relations'),
        ),
        migrations.AlterField(
            model_name='historicalbankingrelationship',
            name='account_and_securities_statements',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Transaction Statements'),
        ),
        migrations.AlterField(
            model_name='historicalbankingrelationship',
            name='communication_br',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Communication Mode'),
        ),
        migrations.AlterField(
            model_name='historicalbankingrelationship',
            name='type_and_purpose',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Purpose Of Banking Relations'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='no_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Mandate, Discount'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='no_discount_amount_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mandate, Discount Amoun'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='no_flat_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Mandate, Flat Fee'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='no_flat_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mandate, Flat Fee Amount'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='service_and_execution',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Individual', 'Individual')], max_length=255, null=True, verbose_name='Service And Execution'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='transaction_fee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction'),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Mandate, Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_discount_amount_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mandate, Discount Amoun'),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_flat_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Mandate, Flat Fee'),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_flat_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mandate, Flat Fee Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='service_and_execution',
            field=models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Individual', 'Individual')], max_length=255, null=True, verbose_name='Service And Execution'),
        ),
        migrations.AlterField(
            model_name='product',
            name='transaction_fee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction'),
        ),
        migrations.DeleteModel(
            name='HistoricalMeetingPreparation',
        ),
    ]
