# Generated by Django 6.0.5 on 2026-07-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_remove_historicalmeetingpreparation_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='no_discount_amount_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mandate, Discount Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_discount_amount_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mandate, Discount Amount'),
        ),
    ]
