# Generated by Django 6.0.5 on 2026-07-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_alter_historicalproduct_no_discount_amount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankingrelationship',
            name='br_client_type',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Business', 'Business')], max_length=50, null=True, verbose_name='Type of Usage'),
        ),
        migrations.AlterField(
            model_name='bankingrelationship',
            name='segment_type',
            field=models.CharField(blank=True, choices=[('120', '120'), ('132', '132'), ('131', '131')], max_length=255, null=True, verbose_name='Client Type'),
        ),
        migrations.AlterField(
            model_name='historicalbankingrelationship',
            name='br_client_type',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Business', 'Business')], max_length=50, null=True, verbose_name='Type of Usage'),
        ),
        migrations.AlterField(
            model_name='historicalbankingrelationship',
            name='segment_type',
            field=models.CharField(blank=True, choices=[('120', '120'), ('132', '132'), ('131', '131')], max_length=255, null=True, verbose_name='Client Type'),
        ),
    ]
