# Generated by Django 6.0.4 on 2026-05-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0003_le_additionalformde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalle_nationality',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_nationality',
            name='fiscal_code_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_nationality',
            name='id_document_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_nationality',
            name='id_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_nationality',
            name='is_id_document_provided',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_nationality',
            name='is_main_nationality',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_nationality',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_nationality',
            name='nci',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_nationality',
            name='release_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_nationality',
            name='release_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='country_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='country_of_registration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='federal_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='first_and_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='fiscal_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='indication_tin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='industry_sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('AG', 'Aktiengesellschaft (AG)'), ('GmbH', 'Gesellschaft mit beschränkter Haftung (GmbH)'), ('Foundation', 'Foundation'), ('Trust', 'Trust'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='lei_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LEI Code'),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='name_at_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='occupation_sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax ID / VAT'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='investment_amount',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Investment Amount'),
        ),
        migrations.AlterField(
            model_name='historicalle_tin',
            name='aei_tin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AEI/TIN'),
        ),
        migrations.AlterField(
            model_name='le_nationality',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_nationality',
            name='fiscal_code_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_nationality',
            name='id_document_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_nationality',
            name='id_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_nationality',
            name='is_id_document_provided',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='le_nationality',
            name='is_main_nationality',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='le_nationality',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_nationality',
            name='nci',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_nationality',
            name='release_authority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_nationality',
            name='release_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='country_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='country_of_registration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='federal_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='first_and_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='fiscal_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='indication_tin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='industry_sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('AG', 'Aktiengesellschaft (AG)'), ('GmbH', 'Gesellschaft mit beschränkter Haftung (GmbH)'), ('Foundation', 'Foundation'), ('Trust', 'Trust'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='lei_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LEI Code'),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='name_at_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='occupation_sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax ID / VAT'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='investment_amount',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Investment Amount'),
        ),
        migrations.AlterField(
            model_name='le_tin',
            name='aei_tin',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AEI/TIN'),
        ),
    ]
