# Generated by Django 6.0.4 on 2026-05-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0005_historicalle_relationship_relationship_with_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalle_clientadvisor',
            name='desk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='desk'),
        ),
        migrations.AddField(
            model_name='historicalle_ebanking',
            name='has_ebanking',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='has ebanking'),
        ),
        migrations.AddField(
            model_name='historicalle_relationship',
            name='lr_beneficial_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='beneficial owner'),
        ),
        migrations.AddField(
            model_name='historicalle_relationship',
            name='lr_bo_role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='beneficial owner role'),
        ),
        migrations.AddField(
            model_name='historicalle_relationship',
            name='lr_executor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='executor'),
        ),
        migrations.AddField(
            model_name='historicalle_relationship',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='le_clientadvisor',
            name='desk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='desk'),
        ),
        migrations.AddField(
            model_name='le_ebanking',
            name='has_ebanking',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='has ebanking'),
        ),
        migrations.AddField(
            model_name='le_relationship',
            name='lr_beneficial_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='beneficial owner'),
        ),
        migrations.AddField(
            model_name='le_relationship',
            name='lr_bo_role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='beneficial owner role'),
        ),
        migrations.AddField(
            model_name='le_relationship',
            name='lr_executor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='executor'),
        ),
        migrations.AddField(
            model_name='le_relationship',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='all_in',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='All In'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='alternative_investment',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='alternative investment'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='current_return_on_assets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='return'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='direct_instrument',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='direct instrument'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='discount_amount_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='discount percent'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='discount_applied',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='email_waiver',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Email waiver'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='fixed_income_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='fixed discount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='fixed_income_discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fixed discount amount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='fixed_income_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='fixed fee'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='fixed_income_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fixed fee amount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='fixed_income_investment_funds_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='fixed funds discount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='fixed_income_investment_funds_discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fixed funds discount amount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='fixed_income_investment_funds_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='fixed funds fee'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='fixed_income_investment_funds_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fixed funds fee amount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='flat_fee_applied',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='flat fee'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='flat_fee_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='flat percent'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='focus_equity',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Focus'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='income_pa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='income'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='initial_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='initial amount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='invested_assets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='invested'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='investment_fund_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='funds discount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='investment_fund_discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='funds discount amount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='investment_fund_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='funds fee amount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='investment_funds_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='funds fee'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='mandate_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='mandate'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='net_new_money_potential',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='net new'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='no_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='no discount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='no_discount_amount_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='no discount percent'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='no_flat_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='no flat'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='no_flat_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='no flat amount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='shares_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares discount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='shares_discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares discount amount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='shares_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares fee'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='shares_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares fee amount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='shares_investment_funds_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares funds discount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='shares_investment_funds_discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares funds discount amount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='shares_investment_funds_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares funds fee'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='shares_investment_funds_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares funds fee amount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='standard_fee_discount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='standard discount'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='sustainable_investing',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Sustainable Investing'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='target_roa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='target roa'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='transaction_confirmation',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='transaction confirmation'),
        ),
        migrations.AlterField(
            model_name='historicalle_product',
            name='transaction_fee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='transaction fee'),
        ),
        migrations.AlterField(
            model_name='historicalle_relationship',
            name='type_of_relationship',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Co-owner', 'Co-owner'), ('POA (for all accounts)', 'POA (for all accounts)'), ('POA (general)', 'POA (general)'), ('POA (limited)', 'POA (limited)'), ('POA (in case of death)', 'POA (in case of death)'), ('Beneficial Owner', 'Beneficial Owner'), ('Legal Representative', 'Legal Representative')], max_length=100, null=True, verbose_name='relationship'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='all_in',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='All In'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='alternative_investment',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='alternative investment'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='current_return_on_assets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='return'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='direct_instrument',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='direct instrument'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='discount_amount_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='discount percent'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='discount_applied',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='email_waiver',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Email waiver'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='fixed_income_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='fixed discount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='fixed_income_discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fixed discount amount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='fixed_income_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='fixed fee'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='fixed_income_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fixed fee amount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='fixed_income_investment_funds_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='fixed funds discount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='fixed_income_investment_funds_discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fixed funds discount amount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='fixed_income_investment_funds_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='fixed funds fee'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='fixed_income_investment_funds_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fixed funds fee amount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='flat_fee_applied',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='flat fee'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='flat_fee_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='flat percent'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='focus_equity',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Focus'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='income_pa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='income'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='initial_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='initial amount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='invested_assets',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='invested'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='investment_fund_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='funds discount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='investment_fund_discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='funds discount amount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='investment_fund_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='funds fee amount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='investment_funds_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='funds fee'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='mandate_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='mandate'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='net_new_money_potential',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='net new'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='no_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='no discount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='no_discount_amount_percent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='no discount percent'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='no_flat_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='no flat'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='no_flat_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='no flat amount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='shares_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares discount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='shares_discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares discount amount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='shares_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares fee'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='shares_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares fee amount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='shares_investment_funds_discount',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares funds discount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='shares_investment_funds_discount_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares funds discount amount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='shares_investment_funds_fee',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='shares funds fee'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='shares_investment_funds_fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='shares funds fee amount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='standard_fee_discount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='standard discount'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='sustainable_investing',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Sustainable Investing'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='target_roa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='target roa'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='transaction_confirmation',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='transaction confirmation'),
        ),
        migrations.AlterField(
            model_name='le_product',
            name='transaction_fee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='transaction fee'),
        ),
        migrations.AlterField(
            model_name='le_relationship',
            name='type_of_relationship',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Co-owner', 'Co-owner'), ('POA (for all accounts)', 'POA (for all accounts)'), ('POA (general)', 'POA (general)'), ('POA (limited)', 'POA (limited)'), ('POA (in case of death)', 'POA (in case of death)'), ('Beneficial Owner', 'Beneficial Owner'), ('Legal Representative', 'Legal Representative')], max_length=100, null=True, verbose_name='relationship'),
        ),
    ]
