# Generated by Django 6.0.5 on 2026-05-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0006_historicalle_clientadvisor_desk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalle_additionalformde',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='historicalle_nationality',
            name='is_id_document_provided',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_nationality',
            name='is_main_nationality',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='beneficial_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='executor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='sensitive_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_personalinformation',
            name='tef',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_additionalformde',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='le_nationality',
            name='is_id_document_provided',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_nationality',
            name='is_main_nationality',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='beneficial_owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='executor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='sensitive_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_personalinformation',
            name='tef',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
