# Generated by Django 6.0.5 on 2026-05-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0007_alter_historicalle_additionalformde_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalle_ebanking',
            name='first_and_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='first and last name'),
        ),
        migrations.AddField(
            model_name='le_ebanking',
            name='first_and_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='first and last name'),
        ),
    ]
