# Generated by Django 6.0.5 on 2026-05-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0008_historicalle_ebanking_first_and_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalle_bankingrelationship',
            name='type_of_account',
        ),
        migrations.RemoveField(
            model_name='historicalle_bankingrelationship',
            name='type_of_signature',
        ),
        migrations.RemoveField(
            model_name='historicalle_relationship',
            name='tax_domicile',
        ),
        migrations.RemoveField(
            model_name='le_bankingrelationship',
            name='type_of_account',
        ),
        migrations.RemoveField(
            model_name='le_bankingrelationship',
            name='type_of_signature',
        ),
        migrations.RemoveField(
            model_name='le_relationship',
            name='tax_domicile',
        ),
        migrations.AddField(
            model_name='historicalle_relationship',
            name='lr_bo_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='beneficial owner reason'),
        ),
        migrations.AddField(
            model_name='le_relationship',
            name='lr_bo_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='beneficial owner reason'),
        ),
        migrations.AlterField(
            model_name='historicalle_ebanking',
            name='contract_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='contract'),
        ),
        migrations.AlterField(
            model_name='le_ebanking',
            name='contract_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='contract'),
        ),
    ]
