# Generated by Django 6.0.5 on 2026-05-11 08:42

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0009_remove_historicalle_bankingrelationship_type_of_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLE_TaxDomicile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('client_uuid', models.UUIDField(db_index=True)),
                ('aei_tin', models.CharField(blank=True, max_length=255, null=True, verbose_name='AEI/TIN')),
                ('fiscal_residence', models.CharField(blank=True, max_length=255, null=True, verbose_name='fiscal residence')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('tin_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='TIN number')),
                ('no_tin_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='no TIN reason')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tax Domicile',
                'verbose_name_plural': 'historical Tax Domicile',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LE_TaxDomicile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_uuid', models.UUIDField(db_index=True)),
                ('aei_tin', models.CharField(blank=True, max_length=255, null=True, verbose_name='AEI/TIN')),
                ('fiscal_residence', models.CharField(blank=True, max_length=255, null=True, verbose_name='fiscal residence')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('tin_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='TIN number')),
                ('no_tin_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='no TIN reason')),
            ],
            options={
                'verbose_name': 'Tax Domicile',
                'verbose_name_plural': 'Tax Domicile',
            },
        ),
        migrations.RemoveField(
            model_name='historicalle_tin',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='LE_TIN',
        ),
        migrations.AlterField(
            model_name='historicalle_relationship',
            name='first_and_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='first and last name'),
        ),
        migrations.AlterField(
            model_name='le_relationship',
            name='first_and_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='first and last name'),
        ),
        migrations.DeleteModel(
            name='HistoricalLE_TIN',
        ),
    ]
