# Generated by Django 6.0.5 on 2026-05-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0010_historicalle_taxdomicile_le_taxdomicile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalle_company',
            name='fiscal_residence',
        ),
        migrations.RemoveField(
            model_name='historicalle_nationality',
            name='fiscal_code',
        ),
        migrations.RemoveField(
            model_name='historicalle_nationality',
            name='fiscal_code_path',
        ),
        migrations.RemoveField(
            model_name='historicalle_personalinformation',
            name='fiscal_identifier',
        ),
        migrations.RemoveField(
            model_name='historicalle_taxdomicile',
            name='fiscal_residence',
        ),
        migrations.RemoveField(
            model_name='le_company',
            name='fiscal_residence',
        ),
        migrations.RemoveField(
            model_name='le_nationality',
            name='fiscal_code',
        ),
        migrations.RemoveField(
            model_name='le_nationality',
            name='fiscal_code_path',
        ),
        migrations.RemoveField(
            model_name='le_personalinformation',
            name='fiscal_identifier',
        ),
        migrations.RemoveField(
            model_name='le_taxdomicile',
            name='fiscal_residence',
        ),
        migrations.AddField(
            model_name='historicalle_company',
            name='fiscal_code_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fiscal Code (IT)'),
        ),
        migrations.AddField(
            model_name='historicalle_taxdomicile',
            name='fiscal_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fiscal identifier'),
        ),
        migrations.AddField(
            model_name='historicalle_taxdomicile',
            name='tax_domicile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tax domicile'),
        ),
        migrations.AddField(
            model_name='le_company',
            name='fiscal_code_it',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fiscal Code (IT)'),
        ),
        migrations.AddField(
            model_name='le_taxdomicile',
            name='fiscal_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='fiscal identifier'),
        ),
        migrations.AddField(
            model_name='le_taxdomicile',
            name='tax_domicile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tax domicile'),
        ),
        migrations.AlterField(
            model_name='historicalle_address',
            name='type_of_address',
            field=models.CharField(blank=True, choices=[('Correspondence', 'Correspondence'), ('Domicile', 'Domicile'), ('Legal Address', 'Legal Address'), ('Residence', 'Residence'), ('Tax domicile', 'Tax domicile'), ('Fiscal residence', 'Fiscal residence'), ('Third party', 'Third party')], max_length=100, null=True, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='historicalle_nationality',
            name='id_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='type of identification (NCI)'),
        ),
        migrations.AlterField(
            model_name='le_address',
            name='type_of_address',
            field=models.CharField(blank=True, choices=[('Correspondence', 'Correspondence'), ('Domicile', 'Domicile'), ('Legal Address', 'Legal Address'), ('Residence', 'Residence'), ('Tax domicile', 'Tax domicile'), ('Fiscal residence', 'Fiscal residence'), ('Third party', 'Third party')], max_length=100, null=True, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='le_nationality',
            name='id_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='type of identification (NCI)'),
        ),
    ]
