# Generated by Django 6.0.5 on 2026-05-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0011_remove_historicalle_company_fiscal_residence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalle_bankingrelationship',
            name='fiscal_identifier',
        ),
        migrations.RemoveField(
            model_name='historicalle_taxdomicile',
            name='aei_tin',
        ),
        migrations.RemoveField(
            model_name='le_bankingrelationship',
            name='fiscal_identifier',
        ),
        migrations.RemoveField(
            model_name='le_taxdomicile',
            name='aei_tin',
        ),
        migrations.AlterField(
            model_name='historicalle_relationship',
            name='type_of_relationship',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Co-owner', 'Co-owner'), ('POA (for all accounts)', 'POA (for all accounts)'), ('POA (general)', 'POA (general)'), ('POA (limited)', 'POA (limited)'), ('POA (in case of death)', 'POA (in case of death)'), ('Beneficial Owner', 'Beneficial Owner'), ('Legal Representative', 'Legal Representative'), ('Legal Representative + Beneficial Owner', 'Legal Representative + Beneficial Owner')], max_length=100, null=True, verbose_name='relationship'),
        ),
        migrations.AlterField(
            model_name='le_relationship',
            name='type_of_relationship',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Co-owner', 'Co-owner'), ('POA (for all accounts)', 'POA (for all accounts)'), ('POA (general)', 'POA (general)'), ('POA (limited)', 'POA (limited)'), ('POA (in case of death)', 'POA (in case of death)'), ('Beneficial Owner', 'Beneficial Owner'), ('Legal Representative', 'Legal Representative'), ('Legal Representative + Beneficial Owner', 'Legal Representative + Beneficial Owner')], max_length=100, null=True, verbose_name='relationship'),
        ),
    ]
