# Generated by Django 6.0.5 on 2026-06-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0012_remove_historicalle_bankingrelationship_fiscal_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalle_bankingrelationship',
            name='code_csc',
        ),
        migrations.RemoveField(
            model_name='historicalle_bankingrelationship',
            name='id_doc_provided',
        ),
        migrations.RemoveField(
            model_name='historicalle_product',
            name='alternative_investment',
        ),
        migrations.RemoveField(
            model_name='historicalle_product',
            name='currency_hedging',
        ),
        migrations.RemoveField(
            model_name='historicalle_product',
            name='share_focus',
        ),
        migrations.RemoveField(
            model_name='le_bankingrelationship',
            name='code_csc',
        ),
        migrations.RemoveField(
            model_name='le_bankingrelationship',
            name='id_doc_provided',
        ),
        migrations.RemoveField(
            model_name='le_product',
            name='alternative_investment',
        ),
        migrations.RemoveField(
            model_name='le_product',
            name='currency_hedging',
        ),
        migrations.RemoveField(
            model_name='le_product',
            name='share_focus',
        ),
        migrations.AddField(
            model_name='historicalle_bankingrelationship',
            name='csc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CSC'),
        ),
        migrations.AddField(
            model_name='historicalle_company',
            name='fiduciary_mandate',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Fiduciary mandate'),
        ),
        migrations.AddField(
            model_name='historicalle_relationship',
            name='signature_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='signature type'),
        ),
        migrations.AddField(
            model_name='le_bankingrelationship',
            name='csc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CSC'),
        ),
        migrations.AddField(
            model_name='le_company',
            name='fiduciary_mandate',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Fiduciary mandate'),
        ),
        migrations.AddField(
            model_name='le_relationship',
            name='signature_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='signature type'),
        ),
        migrations.AlterField(
            model_name='historicalle_bankingrelationship',
            name='segment_type',
            field=models.CharField(blank=True, choices=[('241', '241'), ('244', '244'), ('243', '243'), ('231', '231'), ('220', '220'), ('233', '233'), ('232', '232'), ('270', '270'), ('266', '266')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalle_communication',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address (email)'),
        ),
        migrations.AlterField(
            model_name='historicalle_communication',
            name='type_of_comunication',
            field=models.CharField(blank=True, choices=[('Fixed Number', 'Fixed Number'), ('Mobile', 'Mobile'), ('Email', 'Email'), ('Pec address', 'Pec address'), ('Fax', 'Fax')], max_length=255, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='historicalle_relationship',
            name='technical_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BR-Technical Account'),
        ),
        migrations.AlterField(
            model_name='historicalle_relationship',
            name='type_of_relationship',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Co-owner', 'Co-owner'), ('POA (for all accounts)', 'POA (for all accounts)'), ('POA (general)', 'POA (general)'), ('POA (limited)', 'POA (limited)'), ('POA (in case of death)', 'POA (in case of death)'), ('POA (Information)', 'POA (Information)'), ('Beneficial Owner', 'Beneficial Owner'), ('Legal Representative', 'Legal Representative'), ('Legal Representative + Beneficial Owner', 'Legal Representative + Beneficial Owner')], max_length=100, null=True, verbose_name='relationship'),
        ),
        migrations.AlterField(
            model_name='le_bankingrelationship',
            name='segment_type',
            field=models.CharField(blank=True, choices=[('241', '241'), ('244', '244'), ('243', '243'), ('231', '231'), ('220', '220'), ('233', '233'), ('232', '232'), ('270', '270'), ('266', '266')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='le_communication',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address (email)'),
        ),
        migrations.AlterField(
            model_name='le_communication',
            name='type_of_comunication',
            field=models.CharField(blank=True, choices=[('Fixed Number', 'Fixed Number'), ('Mobile', 'Mobile'), ('Email', 'Email'), ('Pec address', 'Pec address'), ('Fax', 'Fax')], max_length=255, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='le_relationship',
            name='technical_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BR-Technical Account'),
        ),
        migrations.AlterField(
            model_name='le_relationship',
            name='type_of_relationship',
            field=models.CharField(blank=True, choices=[('Owner', 'Owner'), ('Co-owner', 'Co-owner'), ('POA (for all accounts)', 'POA (for all accounts)'), ('POA (general)', 'POA (general)'), ('POA (limited)', 'POA (limited)'), ('POA (in case of death)', 'POA (in case of death)'), ('POA (Information)', 'POA (Information)'), ('Beneficial Owner', 'Beneficial Owner'), ('Legal Representative', 'Legal Representative'), ('Legal Representative + Beneficial Owner', 'Legal Representative + Beneficial Owner')], max_length=100, null=True, verbose_name='relationship'),
        ),
    ]
