# Generated by Django 6.0.5 on 2026-06-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0013_remove_historicalle_bankingrelationship_code_csc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalle_address',
            name='type_of_address',
            field=models.CharField(blank=True, choices=[('Correspondence', 'Correspondence'), ('Domicile', 'Domicile'), ('Legal Address', 'Legal Address'), ('Residence', 'Residence'), ('Tax domicile', 'Tax domicile'), ('Fiscal residence', 'Fiscal residence'), ('Third party', 'Third party'), ('Domicile (residenza di pergamena)', 'Domicile (residenza di pergamena)'), ('Correspondence (corrispondenza di pergamena)', 'Correspondence (corrispondenza di pergamena)'), ('Permanent (non in pergamena ma inserito a mano)', 'Permanent (non in pergamena ma inserito a mano)')], max_length=100, null=True, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='le_address',
            name='type_of_address',
            field=models.CharField(blank=True, choices=[('Correspondence', 'Correspondence'), ('Domicile', 'Domicile'), ('Legal Address', 'Legal Address'), ('Residence', 'Residence'), ('Tax domicile', 'Tax domicile'), ('Fiscal residence', 'Fiscal residence'), ('Third party', 'Third party'), ('Domicile (residenza di pergamena)', 'Domicile (residenza di pergamena)'), ('Correspondence (corrispondenza di pergamena)', 'Correspondence (corrispondenza di pergamena)'), ('Permanent (non in pergamena ma inserito a mano)', 'Permanent (non in pergamena ma inserito a mano)')], max_length=100, null=True, verbose_name='address type'),
        ),
    ]
