# Generated by Django 6.0.5 on 2026-06-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0014_alter_historicalle_address_type_of_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalle_account',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='LE_Account',
        ),
        migrations.DeleteModel(
            name='HistoricalLE_Account',
        ),
    ]
