# Generated by Django 6.0.5 on 2026-06-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0015_remove_historicalle_account_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalle_address',
            name='type_of_address',
            field=models.CharField(blank=True, choices=[('Correspondence', 'Correspondence'), ('Domicile', 'Domicile'), ('Legal Residence', 'Legal Residence'), ('Permanent', 'Permanent')], max_length=100, null=True, verbose_name='address type'),
        ),
        migrations.AlterField(
            model_name='le_address',
            name='type_of_address',
            field=models.CharField(blank=True, choices=[('Correspondence', 'Correspondence'), ('Domicile', 'Domicile'), ('Legal Residence', 'Legal Residence'), ('Permanent', 'Permanent')], max_length=100, null=True, verbose_name='address type'),
        ),
    ]
