# Generated by Django 6.0.5 on 2026-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0017_remove_historicalle_personalinformation_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalle_bankingrelationship',
            name='segment_type',
            field=models.CharField(blank=True, choices=[('241', '241'), ('244', '244'), ('243', '243'), ('231', '231'), ('220', '220'), ('233', '233'), ('232', '232'), ('270', '270'), ('266', '266')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='le_bankingrelationship',
            name='segment_type',
            field=models.CharField(blank=True, choices=[('241', '241'), ('244', '244'), ('243', '243'), ('231', '231'), ('220', '220'), ('233', '233'), ('232', '232'), ('270', '270'), ('266', '266')], max_length=255, null=True),
        ),
    ]
