# Generated by Django 6.0.5 on 2026-07-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_le', '0020_alter_historicalle_product_no_discount_amount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalle_bankingrelationship',
            name='br_client_type',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Business', 'Business')], max_length=50, null=True, verbose_name='Type of Usage'),
        ),
        migrations.AlterField(
            model_name='historicalle_bankingrelationship',
            name='segment_type',
            field=models.CharField(blank=True, choices=[('241', '241'), ('244', '244'), ('243', '243'), ('231', '231'), ('220', '220'), ('233', '233'), ('232', '232'), ('270', '270'), ('266', '266')], max_length=255, null=True, verbose_name='Client Type'),
        ),
        migrations.AlterField(
            model_name='le_bankingrelationship',
            name='br_client_type',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Business', 'Business')], max_length=50, null=True, verbose_name='Type of Usage'),
        ),
        migrations.AlterField(
            model_name='le_bankingrelationship',
            name='segment_type',
            field=models.CharField(blank=True, choices=[('241', '241'), ('244', '244'), ('243', '243'), ('231', '231'), ('220', '220'), ('233', '233'), ('232', '232'), ('270', '270'), ('266', '266')], max_length=255, null=True, verbose_name='Client Type'),
        ),
    ]
